GET http://localhost:3000/

###
GET http://localhost:3000/book

###
POST http://localhost:3000/register
content-type: application/json

{
    "email": "tkd2@gmail.com",
    "password": "tkd1234",
    "name": "Tanmoy Krishna Das"
}

###
POST http://localhost:3000/login
content-type: application/json

{
    "email": "tkd2@gmail.com",
    "password": "tkd1234"
}

###
GET http://localhost:3000/logout
content-type: application/json

###
GET http://localhost:3000/profile

###
POST http://localhost:3000/file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="uploadedFile"; filename="api_test.rest"

< ./api_test.rest
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
GET http://localhost:3000/file

###
GET http://localhost:3000/file/file_tkd2@gmail.com_api_test.rest

###
PUT http://localhost:3000/file/file_tkd2@gmail.com_api_test.rest
content-type: application/json

{
    "newFileName": "api.rest"
}

###
DELETE http://localhost:3000/file/file_tkd2@gmail.com_api_test.rest

###
POST http://localhost:3000/fileShare
content-type: application/json

{
    "fileKey": "file_tkd2@gmail.com_api_test.rest",
    "sharedWithEmail": "tkd@gmail.com",
    "name": "Tanmoy Krishna Das (latest)"
}

###
GET http://localhost:3000/fileShare/byFile/file_tkd2@gmail.com_api_test.rest

###
GET http://localhost:3000/fileShare/withMe

###
DELETE http://localhost:3000/fileShare/fileShare_file_tkd2@gmail.com_api_test.rest_tkd@gmail.com
